Adding in the UI tests
dfe-analytical-services/leo-graduate-industry-dashboard pull request #20
Opened 2022-03-18 09:47 UTC by rmbielby

Sorry, it's been a bit slow getting this in! Here's the basic UI testing set up in shinytest. It still needs a few little bits of tidying up, but I'm just wanted to open it up for review at this stage to give you both sight. The tests go through each tab individually and check the output based on a handful of different input combinations for each one. The regional tab creates a bulk load of map data in the output, so that's filtered out of any checks. 

I started off looking into unit tests, but didn't seem to be so many 'unit' level components there to test, so shifted on to UI tests. Happy to look into getting unit tests added in as well.

2022-03-21 16:00 UTC, cjrace requested changes
Couple of small changes to make, and then we need to think about how we're merging this with Charlotte's PR as it's included tidied code so will have created plenty of conflicts

2022-03-21 16:00 UTC, cjrace commented on global.R
>  library(dplyr)
Missing shhh() on a couple of packages

2022-03-21 16:00 UTC, cjrace commented on tests/shinytest/testUI.R
> +app$snapshotInit("testUI", screenshot = TRUE)
I'd change this to screenshot = FALSE as the screenshots create false positives on tests on other machines (my computer had differences in the png's but not the jsons)

2022-03-21 18:25 UTC, cjrace commented
Noticed a concerning thing in the logs that shinytest seems to have failed but the action has passed - looks like we need to look at the code for the GitHub actions to make sure we capture when there's differences found and throw an error out. However we fix this, we should retest all other repos using this (off the top of my head it's just the template, SCAP, and Screener)

2022-03-21 19:03 UTC, rmbielby commented on tests/shinytest/testUI.R
> +app$snapshotInit("testUI", screenshot = TRUE)
Done

2022-03-21 19:04 UTC, rmbielby commented on global.R
>  library(dplyr)
Done

2022-03-22 16:53 UTC, cjrace commented
Includes #1 #3 #7

2022-03-23 15:20 UTC, closed without merging

2022-03-23 15:20 UTC, cjrace commented
Closing in favour of #25 and #27