Cf add industry by subject dropdown
dfe-analytical-services/leo-graduate-industry-dashboard pull request #49
Opened 2022-04-13 12:43 UTC by chfoster

## Pull request overview

Add extra dropdown to the industry by subject tables, close #42.

## Pull request checklist

Please check if your PR fulfils the following:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been run locally and are passing (`run_tests_locally()`)
- [ ] Code is styled according to tidyverse styling (checked locally with `tidy_code()`)

## What is the new behaviour?

A new dropdown has been added to the industry by subject tables that allows users to filter the tables further - to the 3-digit SIC group level rather than just the SECTIONNAME level. The dropdown updates based on the selected SECTIONNAME to only include the appropriate group_names. 
![image](https://user-images.githubusercontent.com/101197790/163181660-404f4b0b-63f5-4410-9d29-1d8a5729fe2b.png)

## Anything else

@rmbielby to look at allowing multiple selections at a later date.

2022-04-20 08:49 UTC, cjrace requested changes
Looks good, seems to work as expected though will be good to get Rich to look over this too from a performance side given the work he's done on other bits.

I think we should add an extra line or two to the UI tests to check that the additional drop produces the results that are expected and that it updates as we want it to based on the industry.

2022-04-21 14:44 UTC, rmbielby commented
Quick suggestion to speed the code up a little:
Whenever you have a group_by()/summarise() combo, it's worth adding .groups="drop" to the summarise as it generally halves the time it takes to run the summarise() function (if you don't set it, summarise just defaults to it anyway, but takes a bit of extra time to decide that). As well, you're never doing any actual sums in the summarises, so the lines where you've got n=sum(count), you should be able to change to n=count.

So for example, the following:
`group_by(sex, subject_name) %>%
summarise(n = sum(count)) %>%`

Should run quicker, but produce the same result, if changed to:

`group_by(sex, subject_name) %>%
summarise(n = count, .groups = "drop") %>%`

2022-04-22 08:05 UTC, chfoster commented
> Quick suggestion to speed the code up a little: Whenever you have a group_by()/summarise() combo, it's worth adding .groups="drop" to the summarise as it generally halves the time it takes to run the summarise() function (if you don't set it, summarise just defaults to it anyway, but takes a bit of extra time to decide that). As well, you're never doing any actual sums in the summarises, so the lines where you've got n=sum(count), you should be able to change to n=count.
> 
> So for example, the following: `group_by(sex, subject_name) %>% summarise(n = sum(count)) %>%`
> 
> Should run quicker, but produce the same result, if changed to:
> 
> `group_by(sex, subject_name) %>% summarise(n = count, .groups = "drop") %>%`

Do you know any lines specifically where this could be changed? I can see it in the regional analysis but I do need to sum there.  In the industry_subject and subject_industry I think it is already changed?

2022-04-22 08:42 UTC, rmbielby commented
> > Quick suggestion to speed the code up a little: Whenever you have a group_by()/summarise() combo, it's worth adding .groups="drop" to the summarise as it generally halves the time it takes to run the summarise() function (if you don't set it, summarise just defaults to it anyway, but takes a bit of extra time to decide that). As well, you're never doing any actual sums in the summarises, so the lines where you've got n=sum(count), you should be able to change to n=count.
> > So for example, the following: `group_by(sex, subject_name) %>% summarise(n = sum(count)) %>%`
> > Should run quicker, but produce the same result, if changed to:
> > `group_by(sex, subject_name) %>% summarise(n = count, .groups = "drop") %>%`
> 
> Do you know any lines specifically where this could be changed? I can see it in the regional analysis but I do need to sum there. In the industry_subject and subject_industry I think it is already changed?

Yep, was just meaning in the industry by subject code. Lines 368, 388, 421, 447 and so on all either have n-sum(count) when there's no summation going on (as far as I could tell, but correct me if I'm wrong!), or have summarise(n=earnings_median) without a .groups="drop" flag.

2022-04-22 10:40 UTC, rmbielby approved these changes

2022-04-22 10:41 UTC, merged