Added formatting to download data to force x's and c's in place of NA…
dfe-analytical-services/leo-graduate-industry-dashboard pull request #71
Opened 2022-05-12 09:09 UTC by rmbielby

Updated the formatting of the downloaded data to properly use c's and x's in place of -10000 and NA.

2022-05-12 12:00 UTC, cjrace requested changes
Still getting NAs in the download - On subject by industry, select ethnicity > physics and astronomy.

![image](https://user-images.githubusercontent.com/52536248/168070039-50cdcd80-be39-4f51-8869-82cf588df5ed.png)

2022-05-12 12:00 UTC, cjrace commented on R/subject_industry.R
> -  print("Here's the output I to check on the null data test:")
Do we still need these console outputs?

2022-05-12 12:00 UTC, cjrace commented on R/subject_industry.R
> -  print(crosstab_text)
Console output?

2022-05-12 12:00 UTC, cjrace commented on server.R
> -    print("Here's the reactive summary text...")
Console output?

2022-05-12 12:00 UTC, cjrace commented on server.R
> +          mutate_all(funs(ifelse(. == "NA", "x", .)))
Is there an alternative to funs() we should be using (I think I've seen that it's deprecated?)

2022-05-12 13:48 UTC, rmbielby commented on server.R
> +          mutate_all(funs(ifelse(. == "NA", "x", .)))
Yep, did look at that separately yesterday elsewhere in the code. Think there were a few options. Will pick one and apply in this case.

2022-05-12 13:52 UTC, cjrace commented
Still seems broken, though in a slightly different way, x's are mostly appearing where there were NAs though some of those are now showing as NaN instead? (Same scenario - on subject by industry, select ethnicity > physics and astronomy)

![image](https://user-images.githubusercontent.com/52536248/168090577-4091ba3f-6fbb-4373-a40b-19ba6f1d9ecb.png)

2022-05-12 13:54 UTC, rmbielby commented on server.R
> +          mutate_all(funs(ifelse(. == "NA", "x", .)))
Have switched these instances from funs() to list(~) now.

2022-05-12 14:20 UTC, rmbielby commented
> 

The NaNs look like they originate in the issue that Charlotte raised yesterday whereby proportions should be 0 when we're calculating a proportion of 0/0. They're not doing that in the nested table data at least, so reach the download point as NaNs. In the online tables, they're being processed as x's instead. 

So it's a double bug in that the download gives a Nan and the online tables give and x, but both should be 0.

2022-05-13 10:13 UTC, cjrace approved these changes

2022-05-13 11:02 UTC, merged